// Auto-generated by scripts/px2ansi.js — do not edit manually.
// Regenerate: node scripts/px2ansi.js nain-removebg-preview.png --width 40 --height 50 --eye-row 25 > sprite_out.txt
// Source: nain-removebg-preview.png  |  40 cols × 23 terminal rows  |  eye row 11

import chalk from 'chalk';
import type { CompanionState } from './Companion.js';

// ─── Eye config ───────────────────────────────────────────────────────────────

const EYE_CFG: Record<CompanionState, { sym: string; colorHex: string; spark?: boolean }> = {
  idle: { sym: '◉', colorHex: '#C8A415' }, // amber gold
  thinking: { sym: '◔', colorHex: '#888888' }, // gray
  forging: { sym: '◉', colorHex: '#FF8C00' }, // ember orange
  error: { sym: '✖', colorHex: '#FF4444' }, // red
  done: { sym: '◉', colorHex: '#44CC44', spark: true }, // green
};

// Eye row: 11 columns wide face ~19, padded 11 left / 10 right (detected skin: #101012)
export function eyeLine(state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[state];
  const face = chalk.bgHex('#101012');
  const eye = face.hex(colorHex);
  return (
    ' '.repeat(11) +
    face('    ') +
    eye(sym) +
    face('      ') +
    eye(sym) +
    face('       ') +
    ' '.repeat(10) +
    (spark ? chalk.hex('#C8A415')(' ✦') : '')
  );
}

// ─── Portrait helpers ─────────────────────────────────────────────────────────

// Strip up to n leading literal spaces (safe with ANSI since codes start with \x1b)
function stripLeading(line: string, n: number): string {
  let i = 0;
  while (i < n && i < line.length && line[i] === ' ') i++;
  return line.slice(i);
}

// Strip trailing literal spaces (stops at first non-space, safe with ANSI bg chars)
function stripTrailing(line: string): string {
  let end = line.length;
  while (end > 0 && line[end - 1] === ' ') end--;
  return line.slice(0, end);
}

function cropLine(line: string): string {
  return stripTrailing(stripLeading(line, 9));
}

// Compact portrait — 5 rows (face + eyes), stripped of transparent padding
export function compactPortrait(state: CompanionState): string[] {
  return fullSpriteLines(state).slice(8, 13).map(cropLine);
}

// Full portrait — 14 rows (helmet → beard start), stripped of transparent padding
export function fullPortrait(state: CompanionState): string[] {
  return fullSpriteLines(state).slice(0, 14).map(cropLine);
}

// Eye symbol for micro mode
export function eyeSymbol(state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[state];
  const eye = chalk.hex(colorHex);
  return eye(sym) + ' ' + eye(sym) + (spark ? chalk.hex('#C8A415')(' ✦') : '');
}

// ─── Full sprite (40 cols × 23 terminal rows) ─────────────────────────────────

export function fullSpriteLines(state: CompanionState): string[] {
  return [
    ' '.repeat(18) +
      chalk.bgHex('#828282').hex('#999998')('▄') +
      chalk.hex('#929292')('▄') +
      ' '.repeat(3) +
      chalk.hex('#9c9f9f')('▄') +
      chalk.hex('#b0b1b2')('▄') +
      chalk.bgHex('#7f7f7f').hex('#d3d3d3')('▄') +
      chalk.bgHex('#939393').hex('#eaeae7')('▄') +
      chalk.bgHex('#8a8a87').hex('#989895')('▄') +
      ' '.repeat(12),
    ' '.repeat(17) +
      chalk.bgHex('#a7a7a5').hex('#a9a9a9')('▄') +
      chalk.bgHex('#d6d7d5').hex('#e2e4e3')('▄') +
      chalk.bgHex('#898c89').hex('#868986')('▄') +
      ' '.repeat(1) +
      chalk.hex('#989898')('▄') +
      chalk.bgHex('#9d9b9b').hex('#f7f7f7')('▄') +
      chalk.bgHex('#d7d7d8').hex('#ffffff')('▄') +
      chalk.bgHex('#ffffff').hex('#e3e3e2')('▄') +
      chalk.bgHex('#ececec').hex('#b2b2b2')('▄') +
      chalk.bgHex('#aaaaaa').hex('#aaaaaa')('▀') +
      ' '.repeat(13),
    ' '.repeat(16) +
      chalk.hex('#4d4d45')('▄') +
      chalk.bgHex('#b9bab9').hex('#cbcccb')('▄') +
      chalk.bgHex('#e1e2e3').hex('#d9dad9')('▄') +
      chalk.bgHex('#757979').hex('#959594')('▄') +
      chalk.bgHex('#959591').hex('#b1b2b2')('▄') +
      chalk.bgHex('#dadada').hex('#ffffff')('▄') +
      chalk.bgHex('#ffffff').hex('#d8d8d5')('▄') +
      chalk.bgHex('#c4c4c4').hex('#8e8e8a')('▄') +
      chalk.bgHex('#8d8f8d').hex('#8d8f8d')('▀') +
      ' '.repeat(15),
    ' '.repeat(17) +
      chalk.bgHex('#b7b9b9').hex('#9ea0a0')('▄') +
      chalk.bgHex('#dcdcdc').hex('#dadbd9')('▄') +
      chalk.bgHex('#a6a7a5').hex('#8f8e8d')('▄') +
      chalk.bgHex('#d3d4d3').hex('#e6e6e6')('▄') +
      chalk.bgHex('#fefefd').hex('#bcbcba')('▄') +
      chalk.bgHex('#969894').hex('#606060')('▄') +
      ' '.repeat(17),
    ' '.repeat(18) +
      chalk.bgHex('#babbb9').hex('#817b74')('▄') +
      chalk.bgHex('#d8dcde').hex('#ccb7a0')('▄') +
      chalk.bgHex('#cccdca').hex('#89877f')('▄') +
      chalk.bgHex('#827f7c').hex('#827f7c')('▀') +
      ' '.repeat(18),
    ' '.repeat(10) +
      chalk.hex('#3d3b2f')('▄') +
      chalk.hex('#515040')('▄') +
      ' '.repeat(3) +
      chalk.hex('#171711')('▄') +
      chalk.hex('#212518')('▄') +
      chalk.bgHex('#1f1815').hex('#675030')('▄') +
      chalk.bgHex('#764c2a').hex('#c3814e')('▄') +
      chalk.bgHex('#a76932').hex('#ce9361')('▄') +
      chalk.bgHex('#6a4425').hex('#c98954')('▄') +
      chalk.bgHex('#170e10').hex('#574524')('▄') +
      chalk.bgHex('#000008').hex('#353924')('▄') +
      chalk.hex('#110f0d')('▄') +
      ' '.repeat(3) +
      chalk.hex('#606154')('▄') +
      chalk.hex('#38382e')('▄') +
      ' '.repeat(11),
    ' '.repeat(10) +
      chalk.bgHex('#4a4a3e').hex('#7f6842')('▄') +
      chalk.bgHex('#9f9164').hex('#cfb06b')('▄') +
      chalk.bgHex('#3f311c').hex('#302414')('▄') +
      chalk.hex('#151a15')('▄') +
      chalk.bgHex('#1f2116').hex('#373a1e')('▄') +
      chalk.bgHex('#3a3e1e').hex('#414220')('▄') +
      chalk.bgHex('#5c5d35').hex('#414122')('▄') +
      chalk.bgHex('#a07d4c').hex('#855f37')('▄') +
      chalk.bgHex('#c89459').hex('#c88f54')('▄') +
      chalk.bgHex('#e3b36d').hex('#c99557')('▄') +
      chalk.bgHex('#bd824e').hex('#b67b47')('▄') +
      chalk.bgHex('#89763c').hex('#615129')('▄') +
      chalk.bgHex('#5d5f36').hex('#383b1d')('▄') +
      chalk.bgHex('#3d3e22').hex('#414121')('▄') +
      chalk.bgHex('#1d1d14').hex('#323217')('▄') +
      chalk.hex('#121515')('▄') +
      chalk.bgHex('#201000').hex('#1d0e00')('▄') +
      chalk.bgHex('#a99c74').hex('#d8c17e')('▄') +
      chalk.bgHex('#474943').hex('#917e54')('▄') +
      ' '.repeat(11),
    ' '.repeat(9) +
      chalk.bgHex('#130900').hex('#4c3519')('▄') +
      chalk.bgHex('#bb9e59').hex('#dabb6a')('▄') +
      chalk.bgHex('#ccab68').hex('#a38349')('▄') +
      chalk.bgHex('#210f07').hex('#261307')('▄') +
      chalk.bgHex('#181c14').hex('#111616')('▄') +
      chalk.bgHex('#414222').hex('#282912')('▄') +
      chalk.bgHex('#51512e').hex('#4b4b26')('▄') +
      chalk.bgHex('#3b3f21').hex('#414625')('▄') +
      chalk.bgHex('#7b5a2e').hex('#584f28')('▄') +
      chalk.bgHex('#ba7c4c').hex('#b37a4a')('▄') +
      chalk.bgHex('#b67c4d').hex('#d7a36f')('▄') +
      chalk.bgHex('#b77847').hex('#9f7949')('▄') +
      chalk.bgHex('#5e502a').hex('#494622')('▄') +
      chalk.bgHex('#3b3d1f').hex('#3a3b1d')('▄') +
      chalk.bgHex('#424423').hex('#3c3d1d')('▄') +
      chalk.bgHex('#41411d').hex('#2b2d15')('▄') +
      chalk.bgHex('#181a12').hex('#22221d')('▄') +
      chalk.bgHex('#1c0e00').hex('#0c0000')('▄') +
      chalk.bgHex('#e5cd85').hex('#a38a51')('▄') +
      chalk.bgHex('#c8b06f').hex('#f2d78d')('▄') +
      chalk.bgHex('#100500').hex('#4f3918')('▄') +
      ' '.repeat(10),
    ' '.repeat(9) +
      chalk.bgHex('#6e4d23').hex('#704c22')('▄') +
      chalk.bgHex('#fad77b').hex('#f7db83')('▄') +
      chalk.bgHex('#6d5a34').hex('#c8b06c')('▄') +
      chalk.hex('#583e1f')('▄') +
      chalk.bgHex('#070707').hex('#805427')('▄') +
      chalk.bgHex('#2a2a14').hex('#4e3919')('▄') +
      chalk.bgHex('#4c4d25').hex('#444522')('▄') +
      chalk.bgHex('#414525').hex('#454725')('▄') +
      chalk.bgHex('#4d4925').hex('#514a26')('▄') +
      chalk.bgHex('#ac7041').hex('#ae7143')('▄') +
      chalk.bgHex('#e2b883').hex('#d7aa75')('▄') +
      chalk.bgHex('#9d895b').hex('#9e8859')('▄') +
      chalk.bgHex('#3c3918').hex('#403d1d')('▄') +
      chalk.bgHex('#3b3d20').hex('#424424')('▄') +
      chalk.bgHex('#434422').hex('#3b3c1f')('▄') +
      chalk.bgHex('#232413').hex('#674c22')('▄') +
      chalk.bgHex('#19191f').hex('#67471e')('▄') +
      chalk.hex('#5c3e15')('▄') +
      chalk.bgHex('#6c5e39').hex('#c7a151')('▄') +
      chalk.bgHex('#ffe18a').hex('#ffe086')('▄') +
      chalk.bgHex('#66481e').hex('#6b5023')('▄') +
      ' '.repeat(10),
    ' '.repeat(9) +
      chalk.bgHex('#533c1f').hex('#171717')('▄') +
      chalk.bgHex('#c59b4a').hex('#7c5623')('▄') +
      chalk.bgHex('#f5de8d').hex('#cc9843')('▄') +
      chalk.bgHex('#f2d889').hex('#e4bc64')('▄') +
      chalk.bgHex('#e1ba6b').hex('#c28d48')('▄') +
      chalk.bgHex('#573d19').hex('#442e14')('▄') +
      chalk.bgHex('#414321').hex('#3c3f21')('▄') +
      chalk.bgHex('#484a27').hex('#404322')('▄') +
      chalk.bgHex('#544c27').hex('#554f28')('▄') +
      chalk.bgHex('#ae7143').hex('#aa7042')('▄') +
      chalk.bgHex('#deb07b').hex('#deae7b')('▄') +
      chalk.bgHex('#9b885b').hex('#958056')('▄') +
      chalk.bgHex('#44401e').hex('#434320')('▄') +
      chalk.bgHex('#363a1d').hex('#37381c')('▄') +
      chalk.bgHex('#262611').hex('#2f2f14')('▄') +
      chalk.bgHex('#915e26').hex('#6e4721')('▄') +
      chalk.bgHex('#eac670').hex('#d4a75c')('▄') +
      chalk.bgHex('#ebcc77').hex('#e3ba67')('▄') +
      chalk.bgHex('#fae183').hex('#e0ad57')('▄') +
      chalk.bgHex('#dbb158').hex('#7d5422')('▄') +
      chalk.bgHex('#523f21').hex('#000006')('▄') +
      ' '.repeat(10),
    ' '.repeat(10) +
      chalk.bgHex('#4a3729').hex('#4a3729')('▀') +
      chalk.bgHex('#664d2a').hex('#020a0a')('▄') +
      chalk.bgHex('#6b512a').hex('#040b07')('▄') +
      chalk.bgHex('#60411e').hex('#282b15')('▄') +
      chalk.bgHex('#43391d').hex('#3c3e1e')('▄') +
      chalk.bgHex('#3d3f21').hex('#454725')('▄') +
      chalk.bgHex('#464925').hex('#525630')('▄') +
      chalk.bgHex('#61532c').hex('#72552e')('▄') +
      chalk.bgHex('#ae774a').hex('#c58958')('▄') +
      chalk.bgHex('#c88c5d').hex('#da9e67')('▄') +
      chalk.bgHex('#926339').hex('#b67647')('▄') +
      chalk.bgHex('#4c4a25').hex('#5d4f27')('▄') +
      chalk.bgHex('#434321').hex('#4d5029')('▄') +
      chalk.bgHex('#424321').hex('#3d3f1c')('▄') +
      chalk.bgHex('#4e4020').hex('#4b4f27')('▄') +
      chalk.bgHex('#5a3718').hex('#2d331b')('▄') +
      chalk.bgHex('#634622').hex('#0a110b')('▄') +
      chalk.bgHex('#5c4020').hex('#000007')('▄') +
      chalk.bgHex('#261313').hex('#261313')('▀') +
      ' '.repeat(11),
    eyeLine(state), // row 11 — dynamic eyes
    ' '.repeat(12) +
      chalk.bgHex('#000000').hex('#545550')('▄') +
      chalk.bgHex('#787978').hex('#cacac7')('▄') +
      chalk.bgHex('#f3eeeb').hex('#dddede')('▄') +
      chalk.bgHex('#e5c3ad').hex('#c6cacb')('▄') +
      chalk.bgHex('#cec0b6').hex('#f2f5f5')('▄') +
      chalk.bgHex('#e2e3e8').hex('#ffffff')('▄') +
      chalk.bgHex('#cecfd1').hex('#f6f6f6')('▄') +
      chalk.bgHex('#b0afae').hex('#ebebeb')('▄') +
      chalk.bgHex('#dee0e3').hex('#fefefe')('▄') +
      chalk.bgHex('#d9d5d1').hex('#ffffff')('▄') +
      chalk.bgHex('#e3c4aa').hex('#d8dad9')('▄') +
      chalk.bgHex('#edded3').hex('#c0c3c4')('▄') +
      chalk.bgHex('#fafcfc').hex('#e5e6e6')('▄') +
      chalk.bgHex('#959594').hex('#dadbda')('▄') +
      chalk.bgHex('#5f5f5f').hex('#bdbdbd')('▄') +
      chalk.hex('#909390')('▄') +
      ' '.repeat(12),
    ' '.repeat(11) +
      chalk.bgHex('#676764').hex('#9a9a97')('▄') +
      chalk.bgHex('#aeafab').hex('#e9e9e8')('▄') +
      chalk.bgHex('#dcdcdb').hex('#d1d1cf')('▄') +
      chalk.bgHex('#ebeceb').hex('#dededd')('▄') +
      chalk.bgHex('#f9f9f8').hex('#d4d4d2')('▄') +
      chalk.bgHex('#f3f2f0').hex('#bdbdbb')('▄') +
      chalk.bgHex('#d8d8d5').hex('#cacac8')('▄') +
      chalk.bgHex('#c7c7c5').hex('#f3f2f1')('▄') +
      chalk.bgHex('#b7b7b5').hex('#fbfbfb')('▄') +
      chalk.bgHex('#cacac9').hex('#dddddd')('▄') +
      chalk.bgHex('#ececec').hex('#c7c7c8')('▄') +
      chalk.bgHex('#ffffff').hex('#cdcecf')('▄') +
      chalk.bgHex('#efefef').hex('#d6dada')('▄') +
      chalk.bgHex('#d9dad8').hex('#bbbbb9')('▄') +
      chalk.bgHex('#b1b1b0').hex('#d9d9d8')('▄') +
      chalk.bgHex('#f1f1f1').hex('#f7f7f7')('▄') +
      chalk.bgHex('#dcdcdc').hex('#c8c7c7')('▄') +
      chalk.bgHex('#818181').hex('#858585')('▄') +
      ' '.repeat(11),
    ' '.repeat(11) +
      chalk.bgHex('#bfbfbd').hex('#b9b9b9')('▄') +
      chalk.bgHex('#eff0ef').hex('#b8b9b8')('▄') +
      chalk.bgHex('#e3e3e0').hex('#ededec')('▄') +
      chalk.bgHex('#bfbfbe').hex('#dcdcdd')('▄') +
      chalk.bgHex('#c4c4c2').hex('#b7b7b7')('▄') +
      chalk.bgHex('#f1f1ef').hex('#ececec')('▄') +
      chalk.bgHex('#f7f7f8').hex('#f6f6f5')('▄') +
      chalk.bgHex('#ffffff').hex('#f7f7f7')('▄') +
      chalk.bgHex('#ffffff').hex('#ffffff')('▄') +
      chalk.bgHex('#ffffff').hex('#fffffe')('▄') +
      chalk.bgHex('#fbfbfb').hex('#f0f0ef')('▄') +
      chalk.bgHex('#d4d4d2').hex('#d6d6d4')('▄') +
      chalk.bgHex('#cbcccb').hex('#f6f6f7')('▄') +
      chalk.bgHex('#c9cbcb').hex('#eff0f1')('▄') +
      chalk.bgHex('#f3f4f2').hex('#bfbfbd')('▄') +
      chalk.bgHex('#d2d2d2').hex('#a4a4a4')('▄') +
      chalk.bgHex('#727272').hex('#727272')('▀') +
      ' '.repeat(12),
    ' '.repeat(12) +
      chalk.bgHex('#b7b8b8').hex('#bbbbbb')('▄') +
      chalk.bgHex('#fdfdfe').hex('#bcbcba')('▄') +
      chalk.bgHex('#fcfcfc').hex('#dadad8')('▄') +
      chalk.bgHex('#d5d5d5').hex('#e0e0de')('▄') +
      chalk.bgHex('#adadae').hex('#d7d7d6')('▄') +
      chalk.bgHex('#c8c8c8').hex('#d0d0cf')('▄') +
      chalk.bgHex('#e3e3e2').hex('#c3c3c1')('▄') +
      chalk.bgHex('#fdfdfd').hex('#d5d5d4')('▄') +
      chalk.bgHex('#dddddc').hex('#c2c2c1')('▄') +
      chalk.bgHex('#bebebb').hex('#dddddd')('▄') +
      chalk.bgHex('#dfdfde').hex('#fcfcfc')('▄') +
      chalk.bgHex('#ffffff').hex('#f7f7f6')('▄') +
      chalk.bgHex('#e7e7e7').hex('#b1b2b2')('▄') +
      chalk.bgHex('#afafaf').hex('#afafaf')('▀') +
      ' '.repeat(14),
    ' '.repeat(13) +
      chalk.bgHex('#acacac').hex('#acacb4')('▄') +
      chalk.bgHex('#e8e8e7').hex('#c1c1c1')('▄') +
      chalk.bgHex('#fbfbfb').hex('#d4d4d4')('▄') +
      chalk.bgHex('#ffffff').hex('#e2e2e2')('▄') +
      chalk.bgHex('#f6f6f6').hex('#dfdfdf')('▄') +
      chalk.bgHex('#eaeaea').hex('#c4c4c3')('▄') +
      chalk.bgHex('#d7d7d7').hex('#d0d0d0')('▄') +
      chalk.bgHex('#f3f3f2').hex('#e0e0e0')('▄') +
      chalk.bgHex('#ffffff').hex('#e1e1e1')('▄') +
      chalk.bgHex('#ffffff').hex('#e7e7e7')('▄') +
      chalk.bgHex('#f8f8f7').hex('#c7c7c7')('▄') +
      chalk.bgHex('#b6b6b6').hex('#b0b0b0')('▄') +
      ' '.repeat(15),
    ' '.repeat(15) +
      chalk.bgHex('#a7a7a7').hex('#a7a7a7')('▀') +
      chalk.bgHex('#c2c2c1').hex('#c3c3c3')('▄') +
      chalk.bgHex('#f2f2f2').hex('#c8c9c8')('▄') +
      chalk.bgHex('#e5e5e4').hex('#d4d6d5')('▄') +
      chalk.bgHex('#f1f1f1').hex('#e2e3e2')('▄') +
      chalk.bgHex('#f5f5f5').hex('#d6d8d8')('▄') +
      chalk.bgHex('#c2c3c2').hex('#bfc2c2')('▄') +
      chalk.bgHex('#abaaaa').hex('#abaaaa')('▀') +
      ' '.repeat(17),
    ' '.repeat(17) +
      chalk.bgHex('#717271').hex('#b4b4b4')('▄') +
      chalk.bgHex('#646666').hex('#c8c8c8')('▄') +
      chalk.bgHex('#8e8f8d').hex('#babab9')('▄') +
      chalk.bgHex('#7b7b7b').hex('#999999')('▄') +
      ' '.repeat(19),
    ' '.repeat(15) +
      chalk.hex('#c4c4c4')('▄') +
      chalk.bgHex('#d2d2d2').hex('#f9f9f9')('▄') +
      chalk.bgHex('#ffffff').hex('#ffffff')('▄') +
      chalk.bgHex('#ffffff').hex('#fdfdfd')('▄') +
      chalk.bgHex('#ffffff').hex('#ffffff')('▄') +
      chalk.bgHex('#d8d8d8').hex('#fefefd')('▄') +
      chalk.bgHex('#9d9d9d').hex('#c3c3c3')('▄') +
      ' '.repeat(18),
    ' '.repeat(14) +
      chalk.bgHex('#bcbcbc').hex('#c2c2c2')('▄') +
      chalk.bgHex('#f6f6f6').hex('#eeeeee')('▄') +
      chalk.bgHex('#f9f9f9').hex('#ebebeb')('▄') +
      chalk.bgHex('#fbfbfb').hex('#f5f5f5')('▄') +
      chalk.bgHex('#ffffff').hex('#fcfcfc')('▄') +
      chalk.bgHex('#fdfdfd').hex('#fcfcfc')('▄') +
      chalk.bgHex('#ffffff').hex('#ffffff')('▄') +
      chalk.bgHex('#d0d0ce').hex('#cdcdcc')('▄') +
      ' '.repeat(18),
    ' '.repeat(14) +
      chalk.bgHex('#bbbbbd').hex('#bbbbbd')('▀') +
      chalk.bgHex('#d8dadb').hex('#aeb0b0')('▄') +
      chalk.bgHex('#c9cacb').hex('#b1b2b3')('▄') +
      chalk.bgHex('#dbdbdb').hex('#c1c2c3')('▄') +
      chalk.bgHex('#e5e5e4').hex('#c7c8ca')('▄') +
      chalk.bgHex('#e7e6e6').hex('#cbcbcc')('▄') +
      chalk.bgHex('#f9fafa').hex('#c2c2c1')('▄') +
      chalk.bgHex('#cfcfcd').hex('#c7c7c7')('▄') +
      ' '.repeat(18),
    ' '.repeat(17) +
      chalk.bgHex('#b0b0b2').hex('#b0b0b2')('▀') +
      chalk.bgHex('#b0b0b4').hex('#b0b0b4')('▀') +
      chalk.bgHex('#b5b5b5').hex('#b5b5b5')('▀') +
      chalk.bgHex('#bbbbb5').hex('#bbbbb5')('▀') +
      ' '.repeat(19),
  ];
}
