// Auto-generated by scripts/gen-sprite.ts — do not edit manually.
// Regenerate: npx tsx scripts/gen-sprite.ts assets/calcifer-f4.png --width 34 --eye-row -1
// Source: assets/calcifer-f4.png  |  34 cols × 15 terminal rows  |  eye row -1

import chalk from 'chalk';
import type { CompanionState } from '../theme.js';

// ─── Eye config ───────────────────────────────────────────────────────────────

const EYE_CFG: Record<CompanionState, { sym: string; colorHex: string; spark?: boolean }> = {
  idle: { sym: '◉', colorHex: '#C8A415' },
  thinking: { sym: '◔', colorHex: '#888888' },
  forging: { sym: '◉', colorHex: '#FF8C00' },
  error: { sym: '✖', colorHex: '#FF4444' },
  done: { sym: '◉', colorHex: '#44CC44', spark: true },
};

export function eyeLine(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const face = chalk.bgHex('#d0c080');
  const eye = face.hex(colorHex);
  return (
    face('        ') +
    eye(sym) +
    face('        ') +
    eye(sym) +
    face('        ') +
    (spark ? chalk.hex('#C8A415')(' ✦') : '')
  );
}

export function eyeSymbol(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const eye = chalk.hex(colorHex);
  return eye(sym) + ' ' + eye(sym) + (spark ? chalk.hex('#C8A415')(' ✦') : '');
}

// ─── Full sprite (34 cols × 15 terminal rows) ─────────────────────────────────

export function fullSpriteLines(_state: CompanionState): string[] {
  return [
    ' '.repeat(16) + chalk.hex('#ffffff')('▄') + chalk.hex('#ffffff')('▄') + ' '.repeat(16),
    ' '.repeat(15) + chalk.hex('#c8a621')('▄') + chalk.hex('#d0bc7e')('▀') + ' '.repeat(17),
    ' '.repeat(13) +
      chalk.hex('#efd572')('▀') +
      chalk.bgHex('#c59712').hex('#845c0b')('▄') +
      chalk.hex('#b49225')('▀') +
      chalk.bgHex('#c98a0e').hex('#d9b935')('▄') +
      chalk.bgHex('#c8960f').hex('#eed45c')('▄') +
      chalk.hex('#c8a013')('▄') +
      ' '.repeat(15),
    ' '.repeat(13) +
      chalk.hex('#b86509')('▄') +
      chalk.bgHex('#c79111').hex('#c79011')('▄') +
      chalk.bgHex('#cba51b').hex('#cba81c')('▄') +
      chalk.bgHex('#e7cc56').hex('#fbe375')('▄') +
      chalk.bgHex('#fde57a').hex('#fae276')('▄') +
      chalk.bgHex('#d5b42f').hex('#ebd058')('▄') +
      chalk.bgHex('#c88b11').hex('#c89411')('▄') +
      chalk.hex('#c6770c')('▄') +
      ' '.repeat(13),
    ' '.repeat(12) +
      chalk.bgHex('#902c00').hex('#b03800')('▄') +
      chalk.bgHex('#bd6608').hex('#be6509')('▄') +
      chalk.bgHex('#c58f11').hex('#c58b11')('▄') +
      chalk.bgHex('#caa51a').hex('#dbb939')('▄') +
      chalk.bgHex('#fae173').hex('#f9e071')('▄') +
      chalk.bgHex('#fae274').hex('#fce888')('▄') +
      chalk.bgHex('#f8df70').hex('#f8de6f')('▄') +
      chalk.bgHex('#d7b040').hex('#d7ad45')('▄') +
      chalk.bgHex('#c67c0d').hex('#b36b0c')('▄') +
      ' '.repeat(13),
    ' '.repeat(11) +
      chalk.bgHex('#771a00').hex('#8e2200')('▄') +
      chalk.bgHex('#ad3600').hex('#aa3400')('▄') +
      chalk.bgHex('#bc5f07').hex('#ba5706')('▄') +
      chalk.bgHex('#c3830f').hex('#c2790c')('▄') +
      chalk.bgHex('#f6dc6d').hex('#f6da6c')('▄') +
      chalk.bgHex('#fbe786').hex('#fae685')('▄') +
      chalk.bgHex('#fbe787').hex('#fae685')('▄') +
      chalk.bgHex('#f7dd6e').hex('#f6db6d')('▄') +
      chalk.bgHex('#dfb550').hex('#eecb66')('▄') +
      chalk.bgHex('#bf6c0a').hex('#bd6408')('▄') +
      chalk.bgHex('#973801').hex('#b23d01')('▄') +
      chalk.hex('#621700')('▄') +
      ' '.repeat(11),
    ' '.repeat(11) +
      chalk.bgHex('#8b2000').hex('#861d00')('▄') +
      chalk.bgHex('#a53100').hex('#9e2d00')('▄') +
      chalk.bgHex('#b84d03').hex('#1a0800')('▄') +
      chalk.bgHex('#98580b').hex('#210c00')('▄') +
      chalk.bgHex('#200e03').hex('#220c00')('▄') +
      chalk.bgHex('#1a0800').hex('#220c00')('▄') +
      chalk.bgHex('#1a0800').hex('#220c00')('▄') +
      chalk.bgHex('#1a0800').hex('#220c00')('▄') +
      chalk.bgHex('#5e4822').hex('#220c00')('▄') +
      chalk.bgHex('#bb5806').hex('#1d0900')('▄') +
      chalk.bgHex('#ad3901').hex('#361000')('▄') +
      chalk.bgHex('#902300').hex('#8b2000')('▄') +
      chalk.hex('#5d1400')('▄') +
      ' '.repeat(10),
    ' '.repeat(11) +
      chalk.bgHex('#811a00').hex('#7e1700')('▄') +
      chalk.bgHex('#1a0800').hex('#0c0400')('▄') +
      chalk.bgHex('#0a0300').hex('#c8a415')('▄') +
      chalk.bgHex('#0b0400').hex('#c8a415')('▄') +
      chalk.bgHex('#0a0300').hex('#c8a415')('▄') +
      chalk.bgHex('#220c00').hex('#0d0400')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#1d0b00').hex('#0c0400')('▄') +
      chalk.bgHex('#0a0300').hex('#c8a415')('▄') +
      chalk.bgHex('#0b0400').hex('#c8a415')('▄') +
      chalk.bgHex('#0d0400').hex('#846a0d')('▄') +
      chalk.bgHex('#451100').hex('#190800')('▄') +
      chalk.bgHex('#600f00').hex('#611100')('▄') +
      ' '.repeat(10),
    ' '.repeat(11) +
      chalk.bgHex('#310b00').hex('#1a0800')('▄') +
      chalk.bgHex('#241903').hex('#0a0300')('▄') +
      chalk.bgHex('#a1600c').hex('#be9212')('▄') +
      chalk.bgHex('#7a1800').hex('#7a1800')('▄') +
      chalk.bgHex('#a2600b').hex('#bf9312')('▄') +
      chalk.bgHex('#231803').hex('#0a0300')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#c8a415').hex('#7f660d')('▄') +
      chalk.bgHex('#a46151').hex('#822702')('▄') +
      chalk.bgHex('#7a1800').hex('#7a1800')('▄') +
      chalk.bgHex('#c8a415').hex('#c8a415')('▄') +
      chalk.bgHex('#0b0400').hex('#110600')('▄') +
      ' '.repeat(11),
    ' '.repeat(11) +
      chalk.hex('#2e0f00')('▀') +
      chalk.bgHex('#1b0900').hex('#1a0800')('▄') +
      chalk.bgHex('#0a0300').hex('#210b00')('▄') +
      chalk.bgHex('#443406').hex('#220c00')('▄') +
      chalk.bgHex('#0a0300').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#170700').hex('#220c00')('▄') +
      chalk.bgHex('#201602').hex('#220c00')('▄') +
      chalk.bgHex('#443406').hex('#220c00')('▄') +
      chalk.bgHex('#0a0300').hex('#1b0900')('▄') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      ' '.repeat(11),
    ' '.repeat(12) +
      chalk.hex('#1c0900')('▀') +
      chalk.bgHex('#1a0800').hex('#200a00')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1b0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#200b00').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#6c2200')('▄') +
      chalk.hex('#702300')('▀') +
      ' '.repeat(11),
    ' '.repeat(14) +
      chalk.hex('#802000')('▀') +
      chalk.bgHex('#531000').hex('#701800')('▄') +
      chalk.bgHex('#1c0900').hex('#711400')('▄') +
      chalk.bgHex('#1a0800').hex('#731400')('▄') +
      chalk.bgHex('#280a00').hex('#711500')('▄') +
      chalk.hex('#641200')('▀') +
      ' '.repeat(14),
    ' '.repeat(15) +
      chalk.hex('#982e00')('▄') +
      chalk.bgHex('#6b1400').hex('#8c2500')('▄') +
      chalk.bgHex('#731600').hex('#6c1900')('▄') +
      chalk.bgHex('#651500').hex('#922600')('▄') +
      ' '.repeat(15),
    ' '.repeat(11) +
      chalk.hex('#7c1c00')('▄') +
      chalk.bgHex('#801d00').hex('#7f1c00')('▄') +
      chalk.bgHex('#b37a0e').hex('#b27b0e')('▄') +
      chalk.bgHex('#801d00').hex('#7f1d00')('▄') +
      chalk.bgHex('#811d00').hex('#7f1d00')('▄') +
      chalk.bgHex('#811d00').hex('#801d00')('▄') +
      chalk.bgHex('#811d00').hex('#dc6e00')('▄') +
      chalk.bgHex('#811d00').hex('#801d00')('▄') +
      chalk.bgHex('#801d00').hex('#7f1d00')('▄') +
      chalk.bgHex('#801d00').hex('#7f1d00')('▄') +
      chalk.bgHex('#a25f0a').hex('#a2610a')('▄') +
      chalk.bgHex('#7f1e00').hex('#7d1c00')('▄') +
      chalk.hex('#7c1c00')('▄') +
      ' '.repeat(10),
    ' '.repeat(13) +
      chalk.hex('#7f1c00')('▀') +
      chalk.hex('#7e1c00')('▀') +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#7f1c00')('▀') +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#7e1c00')('▀') +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#801e00')('▀') +
      ' '.repeat(12),
  ];
}
