// Auto-generated by scripts/gen-sprite.ts — do not edit manually.
// Regenerate: npx tsx scripts/gen-sprite.ts assets/calcifer-f0.png --width 34 --eye-row -1
// Source: assets/calcifer-f0.png  |  34 cols × 15 terminal rows  |  eye row -1

import chalk from 'chalk';
import type { CompanionState } from '../theme.js';

// ─── Eye config ───────────────────────────────────────────────────────────────

const EYE_CFG: Record<CompanionState, { sym: string; colorHex: string; spark?: boolean }> = {
  idle: { sym: '◉', colorHex: '#C8A415' },
  thinking: { sym: '◔', colorHex: '#888888' },
  forging: { sym: '◉', colorHex: '#FF8C00' },
  error: { sym: '✖', colorHex: '#FF4444' },
  done: { sym: '◉', colorHex: '#44CC44', spark: true },
};

export function eyeLine(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const face = chalk.bgHex('#e0e0e0');
  const eye = face.hex(colorHex);
  return (
    face('        ') +
    eye(sym) +
    face('        ') +
    eye(sym) +
    face('        ') +
    (spark ? chalk.hex('#C8A415')(' ✦') : '')
  );
}

export function eyeSymbol(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const eye = chalk.hex(colorHex);
  return eye(sym) + ' ' + eye(sym) + (spark ? chalk.hex('#C8A415')(' ✦') : '');
}

// ─── Full sprite (34 cols × 15 terminal rows) ─────────────────────────────────

export function fullSpriteLines(_state: CompanionState): string[] {
  return [
    ' '.repeat(17) + chalk.hex('#fcfafa')('▄') + chalk.hex('#ffffff')('▄') + ' '.repeat(15),
    ' '.repeat(16) + chalk.hex('#e5c84d')('▄') + chalk.hex('#e4dfd9')('▀') + ' '.repeat(16),
    ' '.repeat(14) +
      chalk.hex('#dcbd58')('▀') +
      chalk.bgHex('#cca91d').hex('#7e5711')('▄') +
      chalk.hex('#d2af26')('▄') +
      chalk.bgHex('#c79412').hex('#f2d762')('▄') +
      chalk.hex('#ccaa1d')('▄') +
      ' '.repeat(15),
    ' '.repeat(14) +
      chalk.bgHex('#93630b').hex('#c5880f')('▄') +
      chalk.bgHex('#c99e15').hex('#c8a114')('▄') +
      chalk.bgHex('#e1c347').hex('#fae274')('▄') +
      chalk.bgHex('#fde67b').hex('#fce477')('▄') +
      chalk.bgHex('#ddbe3e').hex('#ebd05d')('▄') +
      chalk.bgHex('#c79010').hex('#c79a12')('▄') +
      chalk.hex('#c77d0d')('▄') +
      ' '.repeat(13),
    ' '.repeat(12) +
      chalk.hex('#8c2700')('▄') +
      chalk.bgHex('#bc5d07').hex('#bc5c06')('▄') +
      chalk.bgHex('#c4870f').hex('#c4830e')('▄') +
      chalk.bgHex('#c79e14').hex('#dab638')('▄') +
      chalk.bgHex('#f9e172').hex('#fbe887')('▄') +
      chalk.bgHex('#fbe274').hex('#f9e172')('▄') +
      chalk.bgHex('#fae47d').hex('#f8e173')('▄') +
      chalk.bgHex('#bb8e11').hex('#c99919')('▄') +
      chalk.bgHex('#c8830e').hex('#b6710c')('▄') +
      ' '.repeat(13),
    ' '.repeat(11) +
      chalk.hex('#7f1c00')('▄') +
      chalk.bgHex('#a83200').hex('#a53100')('▄') +
      chalk.bgHex('#ba5706').hex('#b95004')('▄') +
      chalk.bgHex('#c37d0d').hex('#c1730c')('▄') +
      chalk.bgHex('#f8de74').hex('#f7dc73')('▄') +
      chalk.bgHex('#fae786').hex('#fae685')('▄') +
      chalk.bgHex('#f8df70').hex('#f7dd6d')('▄') +
      chalk.bgHex('#f7dd6e').hex('#f7db6d')('▄') +
      chalk.bgHex('#d9ad3e').hex('#eecc65')('▄') +
      chalk.bgHex('#c0720c').hex('#be6a0a')('▄') +
      chalk.bgHex('#ab4204').hex('#b54101')('▄') +
      chalk.hex('#822000')('▄') +
      ' '.repeat(11),
    ' '.repeat(11) +
      chalk.bgHex('#861d00').hex('#821a00')('▄') +
      chalk.bgHex('#a02e00').hex('#9a2900')('▄') +
      chalk.bgHex('#b74703').hex('#1a0800')('▄') +
      chalk.bgHex('#975409').hex('#210c00')('▄') +
      chalk.bgHex('#200e03').hex('#220c00')('▄') +
      chalk.bgHex('#1a0800').hex('#220c00')('▄') +
      chalk.bgHex('#1a0800').hex('#220c00')('▄') +
      chalk.bgHex('#1a0800').hex('#220c00')('▄') +
      chalk.bgHex('#5f4923').hex('#220c00')('▄') +
      chalk.bgHex('#bc5e07').hex('#1d0900')('▄') +
      chalk.bgHex('#b13c01').hex('#361100')('▄') +
      chalk.bgHex('#932500').hex('#8f2200')('▄') +
      chalk.hex('#651200')('▄') +
      ' '.repeat(10),
    ' '.repeat(11) +
      chalk.bgHex('#7e1700').hex('#7a1500')('▄') +
      chalk.bgHex('#1a0800').hex('#0c0400')('▄') +
      chalk.bgHex('#0a0300').hex('#c8a415')('▄') +
      chalk.bgHex('#0b0400').hex('#c8a415')('▄') +
      chalk.bgHex('#0a0300').hex('#c8a415')('▄') +
      chalk.bgHex('#220c00').hex('#0d0400')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#1d0b00').hex('#0c0400')('▄') +
      chalk.bgHex('#0a0300').hex('#c8a415')('▄') +
      chalk.bgHex('#0b0400').hex('#c8a415')('▄') +
      chalk.bgHex('#0d0400').hex('#846a0d')('▄') +
      chalk.bgHex('#461200').hex('#190800')('▄') +
      chalk.bgHex('#671000').hex('#631000')('▄') +
      ' '.repeat(10),
    ' '.repeat(11) +
      chalk.bgHex('#300a00').hex('#1a0800')('▄') +
      chalk.bgHex('#241903').hex('#0a0300')('▄') +
      chalk.bgHex('#a1600c').hex('#be9212')('▄') +
      chalk.bgHex('#7a1800').hex('#7a1800')('▄') +
      chalk.bgHex('#a2600b').hex('#bf9312')('▄') +
      chalk.bgHex('#231803').hex('#0a0300')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#c8a415').hex('#7f660d')('▄') +
      chalk.bgHex('#a46151').hex('#822702')('▄') +
      chalk.bgHex('#7a1800').hex('#7a1800')('▄') +
      chalk.bgHex('#c8a415').hex('#c8a415')('▄') +
      chalk.bgHex('#0b0400').hex('#110600')('▄') +
      chalk.hex('#782100')('▀') +
      ' '.repeat(10),
    ' '.repeat(11) +
      chalk.hex('#2e0f00')('▀') +
      chalk.bgHex('#1b0900').hex('#1a0800')('▄') +
      chalk.bgHex('#0a0300').hex('#210b00')('▄') +
      chalk.bgHex('#443406').hex('#220c00')('▄') +
      chalk.bgHex('#0a0300').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#170700').hex('#220c00')('▄') +
      chalk.bgHex('#201602').hex('#220c00')('▄') +
      chalk.bgHex('#443406').hex('#220c00')('▄') +
      chalk.bgHex('#0a0300').hex('#1b0900')('▄') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      ' '.repeat(11),
    ' '.repeat(12) +
      chalk.hex('#1c0900')('▀') +
      chalk.bgHex('#1a0800').hex('#200a00')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1b0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#200b00').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#6c2200')('▄') +
      chalk.hex('#702300')('▀') +
      ' '.repeat(11),
    ' '.repeat(14) +
      chalk.hex('#802000')('▀') +
      chalk.bgHex('#530f00').hex('#701800')('▄') +
      chalk.bgHex('#1c0900').hex('#721400')('▄') +
      chalk.bgHex('#1a0800').hex('#731500')('▄') +
      chalk.bgHex('#280a00').hex('#711500')('▄') +
      chalk.hex('#641100')('▀') +
      ' '.repeat(14),
    ' '.repeat(14) +
      chalk.hex('#992b00')('▄') +
      chalk.hex('#932700')('▄') +
      chalk.bgHex('#6a1400').hex('#8c2100')('▄') +
      chalk.bgHex('#731600').hex('#6e1700')('▄') +
      chalk.bgHex('#671500').hex('#8f2500')('▄') +
      chalk.hex('#9a2800')('▄') +
      ' '.repeat(14),
    ' '.repeat(9) +
      chalk.hex('#791a00')('▄') +
      chalk.bgHex('#831f00').hex('#7c1b00')('▄') +
      chalk.bgHex('#7d1c00').hex('#7d1c00')('▄') +
      chalk.bgHex('#b1780e').hex('#b0790e')('▄') +
      chalk.bgHex('#7f1d00').hex('#7e1c00')('▄') +
      chalk.bgHex('#801d00').hex('#7d1c00')('▄') +
      chalk.bgHex('#801d00').hex('#7e1c00')('▄') +
      chalk.bgHex('#7f1d00').hex('#7e1c00')('▄') +
      chalk.bgHex('#7f1d00').hex('#db6c00')('▄') +
      chalk.bgHex('#7f1d00').hex('#7e1c00')('▄') +
      chalk.bgHex('#801d00').hex('#7e1c00')('▄') +
      chalk.bgHex('#7e1d00').hex('#7d1c00')('▄') +
      chalk.bgHex('#822401').hex('#812301')('▄') +
      chalk.bgHex('#903f05').hex('#903f05')('▄') +
      chalk.bgHex('#7d1c00').hex('#7d1c00')('▄') +
      chalk.hex('#7d1b00')('▄') +
      chalk.hex('#7a1900')('▄') +
      ' '.repeat(8),
    ' '.repeat(12) +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#7c1c00')('▀') +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#7c1c00')('▀') +
      chalk.hex('#7d1c00')('▀') +
      chalk.hex('#7d1b00')('▀') +
      chalk.hex('#7f1900')('▀') +
      ' '.repeat(11),
  ];
}
