// Auto-generated by scripts/gen-sprite.ts — do not edit manually.
// Regenerate: npx tsx scripts/gen-sprite.ts assets/calcifer-f1.png --width 34 --eye-row -1
// Source: assets/calcifer-f1.png  |  34 cols × 15 terminal rows  |  eye row -1

import chalk from 'chalk';
import type { CompanionState } from '../theme.js';

// ─── Eye config ───────────────────────────────────────────────────────────────

const EYE_CFG: Record<CompanionState, { sym: string; colorHex: string; spark?: boolean }> = {
  idle: { sym: '◉', colorHex: '#C8A415' },
  thinking: { sym: '◔', colorHex: '#888888' },
  forging: { sym: '◉', colorHex: '#FF8C00' },
  error: { sym: '✖', colorHex: '#FF4444' },
  done: { sym: '◉', colorHex: '#44CC44', spark: true },
};

export function eyeLine(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const face = chalk.bgHex('#c0a030');
  const eye = face.hex(colorHex);
  return (
    face('        ') +
    eye(sym) +
    face('        ') +
    eye(sym) +
    face('        ') +
    (spark ? chalk.hex('#C8A415')(' ✦') : '')
  );
}

export function eyeSymbol(_state: CompanionState): string {
  const { sym, colorHex, spark } = EYE_CFG[_state];
  const eye = chalk.hex(colorHex);
  return eye(sym) + ' ' + eye(sym) + (spark ? chalk.hex('#C8A415')(' ✦') : '');
}

// ─── Full sprite (34 cols × 15 terminal rows) ─────────────────────────────────

export function fullSpriteLines(_state: CompanionState): string[] {
  return [
    ' '.repeat(17) + chalk.hex('#ffffff')('▄') + chalk.hex('#ffffff')('▄') + ' '.repeat(15),
    ' '.repeat(16) +
      chalk.hex('#a67b0f')('▄') +
      chalk.bgHex('#c1a02f').hex('#a2822f')('▄') +
      chalk.hex('#ffffff')('▀') +
      ' '.repeat(15),
    ' '.repeat(14) +
      chalk.hex('#ffe87b')('▀') +
      chalk.hex('#d8af4e')('▀') +
      chalk.bgHex('#c3a018').hex('#81560c')('▄') +
      chalk.hex('#cdac21')('▄') +
      chalk.bgHex('#c99612').hex('#f1d761')('▄') +
      chalk.hex('#d5b42e')('▄') +
      ' '.repeat(14),
    ' '.repeat(14) +
      chalk.hex('#b35807')('▄') +
      chalk.bgHex('#aa6a0a').hex('#c2770c')('▄') +
      chalk.bgHex('#c89b14').hex('#c79e14')('▄') +
      chalk.bgHex('#dcc047').hex('#fae173')('▄') +
      chalk.bgHex('#fde67a').hex('#fce477')('▄') +
      chalk.bgHex('#e6c84b').hex('#eace58')('▄') +
      chalk.bgHex('#ceab1f').hex('#d3b128')('▄') +
      chalk.hex('#c78a0f')('▄') +
      ' '.repeat(12),
    ' '.repeat(13) +
      chalk.bgHex('#932b00').hex('#a83300')('▄') +
      chalk.bgHex('#bb5a07').hex('#bb5806')('▄') +
      chalk.bgHex('#c2760b').hex('#c1730b')('▄') +
      chalk.bgHex('#c79b14').hex('#e2be46')('▄') +
      chalk.bgHex('#f9e071').hex('#f8df70')('▄') +
      chalk.bgHex('#fae274').hex('#fce888')('▄') +
      chalk.bgHex('#f9e072').hex('#f8df70')('▄') +
      chalk.bgHex('#dcbf50').hex('#e1c553')('▄') +
      chalk.bgHex('#c88e10').hex('#ba7c0e')('▄') +
      chalk.bgHex('#c8660a').hex('#c96b09')('▄') +
      ' '.repeat(11),
    ' '.repeat(12) +
      chalk.bgHex('#821d00').hex('#881e00')('▄') +
      chalk.bgHex('#a63100').hex('#a32f00')('▄') +
      chalk.bgHex('#b95305').hex('#b84b03')('▄') +
      chalk.bgHex('#bf6c0a').hex('#be6308')('▄') +
      chalk.bgHex('#f6da6c').hex('#f6d86c')('▄') +
      chalk.bgHex('#fae685').hex('#f9e484')('▄') +
      chalk.bgHex('#fbe786').hex('#edd87d')('▄') +
      chalk.bgHex('#f7dd6e').hex('#f6db6d')('▄') +
      chalk.bgHex('#f7dc70').hex('#f6da6c')('▄') +
      chalk.bgHex('#c17b0d').hex('#bf700b')('▄') +
      chalk.bgHex('#b65406').hex('#b84e04')('▄') +
      chalk.hex('#9c2d00')('▄') +
      ' '.repeat(10),
    ' '.repeat(11) +
      chalk.bgHex('#550c00').hex('#560e00')('▄') +
      chalk.bgHex('#851c00').hex('#801900')('▄') +
      chalk.bgHex('#9d2b00').hex('#6f1e00')('▄') +
      chalk.bgHex('#ad3c01').hex('#1c0800')('▄') +
      chalk.bgHex('#1d0a00').hex('#220c00')('▄') +
      chalk.bgHex('#1b0900').hex('#220c00')('▄') +
      chalk.bgHex('#210c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#1f0a00').hex('#220c00')('▄') +
      chalk.bgHex('#1a0800').hex('#220c00')('▄') +
      chalk.bgHex('#2b1201').hex('#210c00')('▄') +
      chalk.bgHex('#b64402').hex('#1a0800')('▄') +
      chalk.bgHex('#9e2c00').hex('#982800')('▄') +
      chalk.bgHex('#661600').hex('#781700')('▄') +
      ' '.repeat(9),
    ' '.repeat(11) +
      chalk.hex('#601100')('▀') +
      chalk.bgHex('#7b1600').hex('#4e0e00')('▄') +
      chalk.bgHex('#1a0800').hex('#120600')('▄') +
      chalk.bgHex('#191002').hex('#c8a415')('▄') +
      chalk.bgHex('#c5a115').hex('#d6bc52')('▄') +
      chalk.bgHex('#c39f14').hex('#b68410')('▄') +
      chalk.bgHex('#0a0300').hex('#70580b')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#170800').hex('#0a0300')('▄') +
      chalk.bgHex('#191002').hex('#c8a415')('▄') +
      chalk.bgHex('#c8a415').hex('#f4ecd4')('▄') +
      chalk.bgHex('#7a620c').hex('#c8a415')('▄') +
      chalk.bgHex('#150600').hex('#0a0300')('▄') +
      chalk.bgHex('#761500').hex('#6d1200')('▄') +
      ' '.repeat(9),
    ' '.repeat(12) +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#0b0300').hex('#1f0a00')('▄') +
      chalk.bgHex('#c8a415').hex('#977b10')('▄') +
      chalk.bgHex('#7b1b00').hex('#c8a415')('▄') +
      chalk.bgHex('#7a1800').hex('#c39c14')('▄') +
      chalk.bgHex('#c8a415').hex('#0c0400')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#2c2004').hex('#0b0400')('▄') +
      chalk.bgHex('#c8a415').hex('#977b10')('▄') +
      chalk.bgHex('#7a1800').hex('#c7a315')('▄') +
      chalk.bgHex('#7a1800').hex('#c8a415')('▄') +
      chalk.bgHex('#1d1302').hex('#0c0400')('▄') +
      chalk.hex('#7d2200')('▀') +
      ' '.repeat(9),
    ' '.repeat(12) +
      chalk.hex('#3e1300')('▀') +
      chalk.bgHex('#1a0800').hex('#1a0800')('▄') +
      chalk.bgHex('#210b00').hex('#1b0800')('▄') +
      chalk.bgHex('#100500').hex('#220c00')('▄') +
      chalk.bgHex('#100500').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#220c00').hex('#220c00')('▄') +
      chalk.bgHex('#210b00').hex('#220c00')('▄') +
      chalk.bgHex('#0d0500').hex('#220c00')('▄') +
      chalk.bgHex('#180800').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#3a1200')('▄') +
      ' '.repeat(10),
    ' '.repeat(13) +
      chalk.hex('#632100')('▀') +
      chalk.hex('#1a0800')('▀') +
      chalk.bgHex('#1a0800').hex('#1d0800')('▄') +
      chalk.bgHex('#220b00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#220c00').hex('#1a0800')('▄') +
      chalk.bgHex('#210b00').hex('#1a0800')('▄') +
      chalk.bgHex('#1a0800').hex('#260a00')('▄') +
      chalk.hex('#1a0800')('▀') +
      ' '.repeat(11),
    ' '.repeat(16) +
      chalk.hex('#6b1200')('▀') +
      chalk.bgHex('#731300').hex('#731500')('▄') +
      chalk.bgHex('#751400').hex('#731600')('▄') +
      chalk.bgHex('#731400').hex('#651300')('▄') +
      chalk.hex('#671200')('▀') +
      ' '.repeat(13),
    ' '.repeat(10) +
      chalk.hex('#7c1b00')('▄') +
      chalk.hex('#7b1c00')('▄') +
      chalk.hex('#a6670b')('▄') +
      chalk.hex('#7e1b00')('▄') +
      chalk.hex('#7d1b00')('▄') +
      chalk.hex('#7e1b00')('▄') +
      chalk.hex('#7d1c00')('▄') +
      chalk.bgHex('#6d1900').hex('#7e1c00')('▄') +
      chalk.bgHex('#7b1b00').hex('#7e1c00')('▄') +
      chalk.hex('#7e1c00')('▄') +
      chalk.hex('#7e1c00')('▄') +
      chalk.hex('#7e1c00')('▄') +
      chalk.hex('#7e1b00')('▄') +
      chalk.hex('#9c5508')('▄') +
      chalk.hex('#7e1b00')('▄') +
      chalk.hex('#7d1b00')('▄') +
      chalk.hex('#811c00')('▄') +
      ' '.repeat(7),
    ' '.repeat(8) +
      chalk.hex('#7a1a00')('▀') +
      chalk.hex('#7b1b00')('▀') +
      chalk.bgHex('#7a1b00').hex('#781a00')('▄') +
      chalk.bgHex('#7b1a00').hex('#7a1b00')('▄') +
      chalk.bgHex('#bb8c11').hex('#7b1a00')('▄') +
      chalk.bgHex('#7d1b00').hex('#7b1a00')('▄') +
      chalk.bgHex('#7c1b00').hex('#7c1c00')('▄') +
      chalk.bgHex('#7d1b00').hex('#7c1b00')('▄') +
      chalk.bgHex('#7d1b00').hex('#7d1b00')('▄') +
      chalk.bgHex('#7e1b00').hex('#7c1b00')('▄') +
      chalk.bgHex('#b94e00').hex('#b74e00')('▄') +
      chalk.bgHex('#7e1b00').hex('#7c1b00')('▄') +
      chalk.bgHex('#7e1b00').hex('#7c1b00')('▄') +
      chalk.bgHex('#7c1b00').hex('#7d1b00')('▄') +
      chalk.bgHex('#7d1b00').hex('#7d1b00')('▄') +
      chalk.bgHex('#bb8c11').hex('#7c1c00')('▄') +
      chalk.bgHex('#883202').hex('#7b1a00')('▄') +
      chalk.bgHex('#7c1c00').hex('#7b1a00')('▄') +
      chalk.bgHex('#7b1a00').hex('#7b1900')('▄') +
      chalk.hex('#7b1a00')('▀') +
      ' '.repeat(6),
    ' '.repeat(34),
  ];
}
